# Generated by Django 4.1.1 on 2022-09-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_shippingaddress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="shipping_rice",
        ),
    ]
