version: "3.7"
services:
  backend:
    restart: always
    container_name: back
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi --workers=4
    env_file: ./backend/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/backend/staticfiles
    ports:
      - "8000:8000"
    networks:
      - net
    depends_on:
      - redis

  nginx:
    build: nginx
    restart: always
    volumes:
      - static_volume:/app/backend/staticfiles
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - net

  redis:
    image: redis:7.0.5-bullseye
    command: redis-server
    ports: 
      - "6379:6379"
    networks:
      - net

  celery:
    restart: always
    build:
      context: ./backend
    command: celery -A  backend worker -l info
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - backend
    networks:
      - net

networks:
  net:
    name: net

volumes:
  static_volume:
