# Generated by Django 4.1.1 on 2022-09-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_pdf_price_id_product_price_id"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_items",
            field=models.ManyToManyField(blank=True, null=True, to="products.product"),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
