# Generated by Django 4.1.1 on 2022-09-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="qty",
            new_name="purchased_qty",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="type",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
