# Generated by Django 4.1.1 on 2022-09-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_order_items_delete_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
    ]
