# Generated by Django 4.1.1 on 2022-09-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="subtotal_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
