# Generated by Django 4.1.1 on 2022-09-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1840s"),
                    (2, "1850s"),
                    (3, "1860s"),
                    (4, "1870s"),
                    (5, "1880s"),
                    (6, "1890s"),
                    (7, "Edwardian"),
                ],
                null=True,
            ),
        ),
    ]
