# Generated by Django 4.1.1 on 2022-09-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pdf_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
