# Generated by Django 4.1.1 on 2022-10-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
