# Generated by Django 4.1.2 on 2022-10-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_review_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pdf_price_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price_id",
        ),
    ]
