export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const STRIPE_PUBLISHABLE_KEY =
  "pk_test_51Lldo7DeRNtpFM5DwxVqrN7djRpJCvyrIJ72qWxrh8MsbK4GaOZL7fNhZgViFgK2MO0Yy3G3e8mIwBLJrmcYScBz00h9nXa09d";

export const ORDER_PAYMENT_INTENT_REQUEST = "ORDER_PAYMENT_INTENT_REQUEST";
export const ORDER_PAYMENT_INTENT_SUCCESS = "ORDER_PAYMENT_INTENT_SUCCESS";
export const ORDER_PAYMENT_INTENT_FAIL = "ORDER_PAYMENT_INTENT_FAIL";

export const ORDER_CONFIRM_URL =
  "http://localhost:3000/order/payment/payment_confirm";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";
export const ORDER_DETAILS_RESET = "ORDER_DETAILS_RESET";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";
export const ORDER_LIST_RESET = "ORDER_LIST_RESET";