export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const STRIPE_PUBLISHABLE_KEY =
  "pk_test_51Lldo7DeRNtpFM5DwxVqrN7djRpJCvyrIJ72qWxrh8MsbK4GaOZL7fNhZgViFgK2MO0Yy3G3e8mIwBLJrmcYScBz00h9nXa09d";

export const ORDER_PAYMENT_INTENT_REQUEST = "ORDER_PAYMENT_INTENT_REQUEST";
export const ORDER_PAYMENT_INTENT_SUCCESS = "ORDER_PAYMENT_INTENT_SUCCESS";
export const ORDER_PAYMENT_INTENT_FAIL = "ORDER_PAYMENT_INTENT_FAIL";
