export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_PASSWORD_RESET_REQUEST = "USER_PASSWORD_RESET_REQUEST";
export const USER_PASSWORD_RESET_SUCCESS = "USER_PASSWORD_RESET_SUCCESS";
export const USER_PASSWORD_RESET_FAIL = "USER_PASSWORD_RESET_FAIL";
export const USER_PASSWORD_RESET_RESET = "USER_PASSWORD_RESET_RESET";

export const USER_PASSWORD_TOKEN_REQUEST = "USER_PASSWORD_TOKEN_REQUEST";
export const USER_PASSWORD_TOKEN_SUCCESS = "USER_PASSWORD_TOKEN_SUCCESS";
export const USER_PASSWORD_TOKEN_FAIL = "USER_PASSWORD_TOKEN_FAIL";
export const USER_PASSWORD_TOKEN_RESET = "USER_PASSWORD_TOKEN_RESET";

export const USER_UPDATE_DETAILS_REQUEST = "USER_UPDATE_DETAILS_REQUEST";
export const USER_UPDATE_DETAILS_SUCCESS = "USER_UPDATE_DETAILS_SUCCESS";
export const USER_UPDATE_DETAILS_FAIL = "USER_UPDATE_DETAILS_FAIL";
export const USER_UPDATE_DETAILS_RESET = "USER_UPDATE_DETAILS_RESET";

export const USER_GET_ADDRESSES_REQUEST = "USER_GET_ADDRESSES_REQUEST";
export const USER_GET_ADDRESSES_SUCCESS = "USER_GET_ADDRESSES_SUCCESS";
export const USER_GET_ADDRESSES_FAIL = "USER_GET_ADDRESSES_FAIL";
export const USER_GET_ADDRESSES_RESET = "USER_GET_ADDRESSES_RESET";

export const USER_GET_ADDRESS_DETAIL_REQUEST =
  "USER_GET_ADDRESS_DETAIL_REQUEST";
export const USER_GET_ADDRESS_DETAIL_SUCCESS =
  "USER_GET_ADDRESS_DETAIL_SUCCESS";
export const USER_GET_ADDRESS_DETAIL_FAIL = "USERGET_ADDRESS_DETAIL_FAIL";
export const USER_GET_ADDRESS_DETAIL_RESET = "USERGET_ADDRESS_DETAIL_RESET";

export const USER_ADD_ADDRESS_REQUEST = "USER_ADD_ADDRESS_REQUEST";
export const USER_ADD_ADDRESS_SUCCESS = "USER_ADD_ADDRESS_SUCCESS";
export const USER_ADD_ADDRESS_FAIL = "USER_ADD_ADDRESS_FAIL";
export const USER_ADD_ADDRESS_RESET = "USER_ADD_ADDRESS_RESET";

export const USER_UPDATE_ADDRESS_REQUEST = "USER_UPDATE_ADDRESS_REQUEST";
export const USER_UPDATE_ADDRESS_SUCCESS = "USER_UPDATE_ADDRESS_SUCCESS";
export const USER_UPDATE_ADDRESS_FAIL = "USER_UPDATE_ADDRESS_FAIL";
export const USER_UPDATE_ADDRESS_RESET = "USER_UPDATE_ADDRESS_RESET";
